default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: Vankha@123
  host: localhost
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: "first-rails"


production:
  <<: *default
  database: "first-rails"
